### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by rgreinho** [softprops/hubcaps#281]
## 🐛 Bug description

I am not sure whether I am using this incorrectly, or missing something in my setup, but I was unable to run the examples. I tried the `labels` and the `issues` examples. They both fail in the same way.

#### 🤔 Expected Behavior

I expected to be able to run the examples.

#### 👟 Steps to reproduce

Commands:
```
cd /tmp
cargo new hubcaps-labels
cd hubcaps-labels/
cargo add hubcaps futures pretty_env_logger log
cargo add tokio --features full
cd src/
curl -sL https://raw.githubusercontent.com/softprops/hubcaps/master/examples/labels.rs -o main.rs
cargo run -q
```

Output:
```
thread 'main' panicked at 'not currently running on the Tokio runtime.', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/handle.rs:118:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Cargo.toml
```toml
[package]
name = "hubcaps-labels"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hubcaps = "0.6.2"
futures = "0.3.8"
pretty_env_logger = "0.4.0"
log = "0.4.11"
tokio = { version = "0.3.5", features = ["full"] }
```

#### 🌍 Your environment

hubcaps version: "0.6.2"
